@extends('layouts.master')
@section('title', 'Games')
@section('content')
    <!-- Hero -->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Games</h1>
                <p class="lead fw-normal text-white-50 mb-0">Available games</p>
            </div>
        </div>
    </header>
    <!-- END Hero -->
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium aliquam amet animi architecto blanditiis consectetur dolor dolorum ducimus ea eaque eius esse, excepturi expedita explicabo fugit impedit in ipsa, ipsam maiores modi nulla odio officiis optio quaerat quibusdam ratione reiciendis rem repudiandae rerum suscipit, tempora ullam unde vel veritatis voluptas voluptate. Ab atque delectus deserunt esse eum eveniet explicabo, laboriosam libero perferendis qui? Accusamus adipisci aut commodi delectus deleniti dicta dolores eveniet explicabo fugiat illum impedit, ipsam itaque magni minima nam nesciunt nulla officia pariatur recusandae rerum sit vel veritatis voluptatum. Accusantium asperiores cupiditate, eaque et inventore magni maxime nihil nobis non officia, quod reiciendis, tempore. Accusamus amet aperiam architecto consequuntur distinctio dolor esse magnam, magni perferendis tenetur ullam voluptatibus. Autem, cumque, nulla. Autem eum exercitationem, illo magni omnis perspiciatis reprehenderit sunt veritatis. Adipisci architecto consectetur, cupiditate deserunt dolorem ea error fugit illo itaque laudantium molestias mollitia necessitatibus nihil porro quia repellat rerum saepe sit tempora tenetur veritatis voluptatibus voluptatum. Beatae deleniti dolore doloremque earum inventore iusto modi molestias sit tempore vel. A amet animi assumenda beatae consequuntur corporis, cupiditate debitis dignissimos doloremque dolores ducimus, eligendi eveniet fugiat id ipsum iusto maiores modi natus nisi nulla obcaecati officiis perferendis perspiciatis quam ratione sequi similique sint tempora tenetur totam. Aliquam commodi, deserunt incidunt ipsam labore molestiae necessitatibus quam qui quidem quos repellendus, sapiente! Ab accusamus dolorum eaque enim esse officiis, quidem reiciendis ullam veniam. A ad, at blanditiis dignissimos doloribus, ipsa nesciunt nobis, numquam omnis recusandae temporibus ullam ut voluptates.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium aliquam amet animi architecto blanditiis consectetur dolor dolorum ducimus ea eaque eius esse, excepturi expedita explicabo fugit impedit in ipsa, ipsam maiores modi nulla odio officiis optio quaerat quibusdam ratione reiciendis rem repudiandae rerum suscipit, tempora ullam unde vel veritatis voluptas voluptate. Ab atque delectus deserunt esse eum eveniet explicabo, laboriosam libero perferendis qui? Accusamus adipisci aut commodi delectus deleniti dicta dolores eveniet explicabo fugiat illum impedit, ipsam itaque magni minima nam nesciunt nulla officia pariatur recusandae rerum sit vel veritatis voluptatum. Accusantium asperiores cupiditate, eaque et inventore magni maxime nihil nobis non officia, quod reiciendis, tempore. Accusamus amet aperiam architecto consequuntur distinctio dolor esse magnam, magni perferendis tenetur ullam voluptatibus. Autem, cumque, nulla. Autem eum exercitationem, illo magni omnis perspiciatis reprehenderit sunt veritatis. Adipisci architecto consectetur, cupiditate deserunt dolorem ea error fugit illo itaque laudantium molestias mollitia necessitatibus nihil porro quia repellat rerum saepe sit tempora tenetur veritatis voluptatibus voluptatum. Beatae deleniti dolore doloremque earum inventore iusto modi molestias sit tempore vel. A amet animi assumenda beatae consequuntur corporis, cupiditate debitis dignissimos doloremque dolores ducimus, eligendi eveniet fugiat id ipsum iusto maiores modi natus nisi nulla obcaecati officiis perferendis perspiciatis quam ratione sequi similique sint tempora tenetur totam. Aliquam commodi, deserunt incidunt ipsam labore molestiae necessitatibus quam qui quidem quos repellendus, sapiente! Ab accusamus dolorum eaque enim esse officiis, quidem reiciendis ullam veniam. A ad, at blanditiis dignissimos doloribus, ipsa nesciunt nobis, numquam omnis recusandae temporibus ullam ut voluptates.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium aliquam amet animi architecto blanditiis consectetur dolor dolorum ducimus ea eaque eius esse, excepturi expedita explicabo fugit impedit in ipsa, ipsam maiores modi nulla odio officiis optio quaerat quibusdam ratione reiciendis rem repudiandae rerum suscipit, tempora ullam unde vel veritatis voluptas voluptate. Ab atque delectus deserunt esse eum eveniet explicabo, laboriosam libero perferendis qui? Accusamus adipisci aut commodi delectus deleniti dicta dolores eveniet explicabo fugiat illum impedit, ipsam itaque magni minima nam nesciunt nulla officia pariatur recusandae rerum sit vel veritatis voluptatum. Accusantium asperiores cupiditate, eaque et inventore magni maxime nihil nobis non officia, quod reiciendis, tempore. Accusamus amet aperiam architecto consequuntur distinctio dolor esse magnam, magni perferendis tenetur ullam voluptatibus. Autem, cumque, nulla. Autem eum exercitationem, illo magni omnis perspiciatis reprehenderit sunt veritatis. Adipisci architecto consectetur, cupiditate deserunt dolorem ea error fugit illo itaque laudantium molestias mollitia necessitatibus nihil porro quia repellat rerum saepe sit tempora tenetur veritatis voluptatibus voluptatum. Beatae deleniti dolore doloremque earum inventore iusto modi molestias sit tempore vel. A amet animi assumenda beatae consequuntur corporis, cupiditate debitis dignissimos doloremque dolores ducimus, eligendi eveniet fugiat id ipsum iusto maiores modi natus nisi nulla obcaecati officiis perferendis perspiciatis quam ratione sequi similique sint tempora tenetur totam. Aliquam commodi, deserunt incidunt ipsam labore molestiae necessitatibus quam qui quidem quos repellendus, sapiente! Ab accusamus dolorum eaque enim esse officiis, quidem reiciendis ullam veniam. A ad, at blanditiis dignissimos doloribus, ipsa nesciunt nobis, numquam omnis recusandae temporibus ullam ut voluptates.</p>

@endsection
